#!/usr/bin/env python3
"""
Generate rich French descriptions for all OSM tags.
Uses multiple sources: existing fr-improved.json, wiki FR, and comprehensive dictionaries.
Goal: Create descriptions rich enough for smaller LLMs to match user queries.
"""

import json
import re

INPUT_FILE = "data/osm_tags_complete.json"
FR_IMPROVED_FILE = "data/fr-improved.json"
OUTPUT_FILE = "data/osm_tags_enriched_final.json"

# Comprehensive French translations
TRANSLATIONS = {
    # ===== AMENITY =====
    'animal_boarding': 'Pension pour animaux',
    'animal_breeding': 'Élevage d\'animaux',
    'animal_shelter': 'Refuge pour animaux',
    'animal_training': 'Dressage d\'animaux',
    'archive': 'Archives',
    'arts_centre': 'Centre artistique',
    'atm': 'Distributeur de billets',
    'baby_hatch': 'Boîte à bébé',
    'baking_oven': 'Four à pain',
    'bank': 'Banque',
    'bar': 'Bar',
    'bbq': 'Barbecue',
    'bench': 'Banc',
    'bicycle_parking': 'Parking vélo',
    'bicycle_rental': 'Location de vélos',
    'bicycle_repair_station': 'Station de réparation vélo',
    'biergarten': 'Jardin à bière',
    'boat_rental': 'Location de bateaux',
    'boat_sharing': 'Bateau partagé',
    'brothel': 'Maison close',
    'bureau_de_change': 'Bureau de change',
    'bus_station': 'Gare routière',
    'cafe': 'Café',
    'car_rental': 'Location de voitures',
    'car_sharing': 'Autopartage',
    'car_wash': 'Station de lavage',
    'casino': 'Casino',
    'charging_station': 'Borne de recharge',
    'childcare': 'Garde d\'enfants',
    'cinema': 'Cinéma',
    'clinic': 'Clinique',
    'clock': 'Horloge publique',
    'college': 'Lycée',
    'community_centre': 'Centre communautaire',
    'conference_centre': 'Centre de conférences',
    'courthouse': 'Tribunal',
    'coworking_space': 'Espace de coworking',
    'crematorium': 'Crématorium',
    'crypt': 'Crypte',
    'dentist': 'Dentiste',
    'dive_centre': 'Centre de plongée',
    'doctors': 'Cabinet médical',
    'dog_toilet': 'Canisette',
    'dojo': 'Dojo',
    'drinking_water': 'Eau potable',
    'driving_school': 'Auto-école',
    'embassy': 'Ambassade',
    'events_venue': 'Salle des fêtes',
    'fast_food': 'Restauration rapide',
    'ferry_terminal': 'Terminal ferry',
    'fire_station': 'Caserne de pompiers',
    'first_aid': 'Premiers secours',
    'food_court': 'Aire de restauration',
    'fountain': 'Fontaine',
    'fuel': 'Station-service',
    'funeral_hall': 'Funérarium',
    'gambling': 'Jeux d\'argent',
    'game_feeding': 'Nourrissage de gibier',
    'give_box': 'Boîte à dons',
    'grave_yard': 'Cimetière',
    'grit_bin': 'Bac à sel',
    'gym': 'Salle de sport',
    'healthcare': 'Établissement de santé',
    'hospital': 'Hôpital',
    'hunting_stand': 'Mirador de chasse',
    'ice_cream': 'Glacier',
    'internet_cafe': 'Cybercafé',
    'karaoke_box': 'Karaoké',
    'kindergarten': 'École maternelle',
    'kneipp_water_cure': 'Bassin Kneipp',
    'language_school': 'École de langues',
    'lavoir': 'Lavoir',
    'letter_box': 'Boîte aux lettres',
    'library': 'Bibliothèque',
    'loading_dock': 'Quai de chargement',
    'lounger': 'Transat',
    'love_hotel': 'Love hotel',
    'marketplace': 'Marché',
    'monastery': 'Monastère',
    'money_transfer': 'Transfert d\'argent',
    'mortuary': 'Morgue',
    'motorcycle_parking': 'Parking moto',
    'music_school': 'École de musique',
    'nightclub': 'Discothèque',
    'nursing_home': 'Maison de retraite',
    'parcel_locker': 'Consigne à colis',
    'parking': 'Parking',
    'parking_entrance': 'Entrée de parking',
    'parking_space': 'Place de parking',
    'payment_terminal': 'Terminal de paiement',
    'pharmacy': 'Pharmacie',
    'photo_booth': 'Photomaton',
    'place_of_mourning': 'Chambre funéraire',
    'place_of_worship': 'Lieu de culte',
    'planetarium': 'Planétarium',
    'police': 'Police',
    'polling_station': 'Bureau de vote',
    'post_box': 'Boîte aux lettres',
    'post_depot': 'Dépôt postal',
    'post_office': 'Bureau de poste',
    'prep_school': 'Classe préparatoire',
    'prison': 'Prison',
    'pub': 'Pub',
    'public_bath': 'Bains publics',
    'public_bookcase': 'Boîte à livres',
    'public_building': 'Bâtiment public',
    'ranger_station': 'Maison forestière',
    'reception_desk': 'Réception',
    'recycling': 'Point de recyclage',
    'refugee_site': 'Camp de réfugiés',
    'register_office': 'État civil',
    'research_institute': 'Institut de recherche',
    'restaurant': 'Restaurant',
    'sanitary_dump_station': 'Station de vidange',
    'school': 'École',
    'shelter': 'Abri',
    'shower': 'Douche',
    'smoking_area': 'Zone fumeur',
    'social_centre': 'Centre social',
    'social_facility': 'Établissement social',
    'spa': 'Spa',
    'stripclub': 'Club de strip-tease',
    'studio': 'Studio',
    'swimming_pool': 'Piscine',
    'swingerclub': 'Club échangiste',
    'table': 'Table',
    'taxi': 'Station de taxi',
    'telephone': 'Cabine téléphonique',
    'theatre': 'Théâtre',
    'toilets': 'Toilettes',
    'townhall': 'Mairie',
    'toy_library': 'Ludothèque',
    'training': 'Centre de formation',
    'university': 'Université',
    'vehicle_inspection': 'Contrôle technique',
    'vending_machine': 'Distributeur automatique',
    'veterinary': 'Vétérinaire',
    'waste_basket': 'Poubelle',
    'waste_disposal': 'Déchetterie',
    'waste_transfer_station': 'Station de transfert',
    'water_point': 'Point d\'eau',
    'watering_place': 'Abreuvoir',

    # ===== SHOP =====
    'agrarian': 'Fournitures agricoles',
    'alcohol': 'Cave à vins',
    'anime': 'Manga et anime',
    'antiques': 'Antiquités',
    'appliance': 'Électroménager',
    'art': 'Galerie d\'art',
    'baby_goods': 'Puériculture',
    'bag': 'Maroquinerie',
    'bakery': 'Boulangerie',
    'bathroom_furnishing': 'Salle de bains',
    'beauty': 'Institut de beauté',
    'bed': 'Literie',
    'beverages': 'Boissons',
    'bicycle': 'Magasin de vélos',
    'bookmaker': 'Bookmaker',
    'books': 'Librairie',
    'boutique': 'Boutique',
    'brewing_supplies': 'Fournitures brassicoles',
    'butcher': 'Boucherie',
    'camera': 'Photo',
    'candles': 'Bougies',
    'cannabis': 'Cannabis',
    'car': 'Concessionnaire auto',
    'car_parts': 'Pièces détachées auto',
    'car_repair': 'Garage automobile',
    'carpet': 'Tapis',
    'catalogue': 'Vente par catalogue',
    'charity': 'Boutique caritative',
    'cheese': 'Fromagerie',
    'chemist': 'Droguerie',
    'chocolate': 'Chocolatier',
    'clothes': 'Vêtements',
    'coffee': 'Café (torréfacteur)',
    'collector': 'Collection',
    'computer': 'Informatique',
    'confectionery': 'Confiserie',
    'convenience': 'Supérette',
    'copyshop': 'Reprographie',
    'cosmetics': 'Cosmétiques',
    'craft': 'Artisanat',
    'curtain': 'Rideaux',
    'dairy': 'Crémerie',
    'deli': 'Traiteur',
    'department_store': 'Grand magasin',
    'dive': 'Plongée',
    'doityourself': 'Bricolage',
    'doors': 'Portes',
    'dry_cleaning': 'Pressing',
    'e-cigarette': 'Cigarette électronique',
    'electrical': 'Électricité',
    'electronics': 'Électronique',
    'erotic': 'Sex-shop',
    'fabric': 'Tissus',
    'farm': 'Produits fermiers',
    'fashion': 'Mode',
    'fashion_accessories': 'Accessoires de mode',
    'fireplace': 'Cheminées',
    'fishing': 'Pêche',
    'florist': 'Fleuriste',
    'frame': 'Encadrement',
    'frozen_food': 'Surgelés',
    'fuel': 'Combustibles',
    'funeral_directors': 'Pompes funèbres',
    'furniture': 'Meubles',
    'games': 'Jeux',
    'garden_centre': 'Jardinerie',
    'garden_furniture': 'Mobilier de jardin',
    'gas': 'Gaz',
    'general': 'Épicerie générale',
    'gift': 'Cadeaux',
    'greengrocer': 'Primeur',
    'hairdresser': 'Coiffeur',
    'hairdresser_supply': 'Fournitures coiffure',
    'hardware': 'Quincaillerie',
    'health_food': 'Diététique',
    'hearing_aids': 'Audioprothésiste',
    'herbalist': 'Herboristerie',
    'hifi': 'Hi-fi',
    'hobby': 'Loisirs créatifs',
    'household_linen': 'Linge de maison',
    'houseware': 'Articles ménagers',
    'hunting': 'Chasse',
    'ice_cream': 'Glacier',
    'interior_decoration': 'Décoration intérieure',
    'jewelry': 'Bijouterie',
    'kiosk': 'Kiosque',
    'kitchen': 'Cuisines',
    'laundry': 'Laverie',
    'leather': 'Cuir',
    'lighting': 'Luminaires',
    'locksmith': 'Serrurier',
    'lottery': 'Loterie',
    'mall': 'Centre commercial',
    'massage': 'Massage',
    'medical_supply': 'Matériel médical',
    'military_surplus': 'Surplus militaire',
    'mobile_phone': 'Téléphonie mobile',
    'model': 'Modélisme',
    'money_lender': 'Prêteur sur gages',
    'motorcycle': 'Motos',
    'motorcycle_repair': 'Réparation moto',
    'music': 'Musique',
    'musical_instrument': 'Instruments de musique',
    'newsagent': 'Presse',
    'nutrition_supplements': 'Compléments alimentaires',
    'optician': 'Opticien',
    'organic': 'Bio',
    'outdoor': 'Plein air',
    'outpost': 'Point relais',
    'paint': 'Peinture',
    'pastry': 'Pâtisserie',
    'pawnbroker': 'Prêteur sur gages',
    'perfumery': 'Parfumerie',
    'pet': 'Animalerie',
    'pet_grooming': 'Toilettage',
    'photo': 'Photo',
    'pottery': 'Poterie',
    'printer_ink': 'Cartouches d\'encre',
    'psychic': 'Voyance',
    'radiotechnics': 'Électronique',
    'religious_articles': 'Articles religieux',
    'rental': 'Location',
    'safety_equipment': 'Équipement de sécurité',
    'seafood': 'Poissonnerie',
    'second_hand': 'Occasion',
    'sewing': 'Couture',
    'shoes': 'Chaussures',
    'shoe_repair': 'Cordonnier',
    'spices': 'Épices',
    'sports': 'Sport',
    'stationery': 'Papeterie',
    'storage_rental': 'Garde-meubles',
    'supermarket': 'Supermarché',
    'tailor': 'Tailleur',
    'tattoo': 'Tatouage',
    'tea': 'Thé',
    'ticket': 'Billetterie',
    'tiles': 'Carrelage',
    'tobacco': 'Tabac',
    'toys': 'Jouets',
    'trade': 'Commerce de gros',
    'travel_agency': 'Agence de voyage',
    'trophy': 'Trophées',
    'tyres': 'Pneus',
    'vacant': 'Local vacant',
    'vacuum_cleaner': 'Aspirateurs',
    'variety_store': 'Bazar',
    'video': 'Vidéo',
    'video_games': 'Jeux vidéo',
    'watches': 'Horlogerie',
    'weapons': 'Armes',
    'wholesale': 'Grossiste',
    'wine': 'Cave à vin',
    'wool': 'Laine',

    # ===== TOURISM =====
    'alpine_hut': 'Refuge de montagne',
    'apartment': 'Appartement',
    'aquarium': 'Aquarium',
    'artwork': 'Œuvre d\'art',
    'attraction': 'Attraction touristique',
    'camp_pitch': 'Emplacement de camping',
    'camp_site': 'Camping',
    'caravan_site': 'Aire de camping-car',
    'chalet': 'Chalet',
    'gallery': 'Galerie',
    'guest_house': 'Chambre d\'hôtes',
    'hostel': 'Auberge de jeunesse',
    'hotel': 'Hôtel',
    'information': 'Information touristique',
    'motel': 'Motel',
    'museum': 'Musée',
    'picnic_site': 'Aire de pique-nique',
    'theme_park': 'Parc d\'attractions',
    'viewpoint': 'Point de vue',
    'wilderness_hut': 'Cabane de refuge',
    'zoo': 'Zoo',

    # ===== LEISURE =====
    'adult_gaming_centre': 'Salle de jeux',
    'amusement_arcade': 'Salle d\'arcade',
    'bandstand': 'Kiosque à musique',
    'beach_resort': 'Station balnéaire',
    'bird_hide': 'Observatoire ornithologique',
    'bleachers': 'Gradins',
    'bowling_alley': 'Bowling',
    'common': 'Terrain communal',
    'dance': 'École de danse',
    'disc_golf_course': 'Disc golf',
    'dog_park': 'Parc canin',
    'escape_game': 'Escape game',
    'firepit': 'Foyer extérieur',
    'fishing': 'Zone de pêche',
    'fitness_centre': 'Salle de sport',
    'fitness_station': 'Station de fitness',
    'garden': 'Jardin',
    'golf_course': 'Golf',
    'hackerspace': 'Hackerspace',
    'horse_riding': 'Centre équestre',
    'ice_rink': 'Patinoire',
    'marina': 'Port de plaisance',
    'miniature_golf': 'Mini-golf',
    'nature_reserve': 'Réserve naturelle',
    'outdoor_seating': 'Terrasse',
    'park': 'Parc',
    'picnic_table': 'Table de pique-nique',
    'pitch': 'Terrain de sport',
    'playground': 'Aire de jeux',
    'slipway': 'Cale de mise à l\'eau',
    'sports_centre': 'Centre sportif',
    'sports_hall': 'Gymnase',
    'stadium': 'Stade',
    'swimming_area': 'Zone de baignade',
    'swimming_pool': 'Piscine',
    'track': 'Piste',
    'trampoline_park': 'Parc de trampolines',
    'water_park': 'Parc aquatique',

    # ===== CUISINE =====
    'afghan': 'afghane',
    'african': 'africaine',
    'american': 'américaine',
    'arab': 'arabe',
    'argentinian': 'argentine',
    'asian': 'asiatique',
    'australian': 'australienne',
    'austrian': 'autrichienne',
    'bagel': 'bagels',
    'balkan': 'balkanique',
    'barbecue': 'barbecue',
    'basque': 'basque',
    'bavarian': 'bavaroise',
    'belgian': 'belge',
    'bowl': 'bowls',
    'brazilian': 'brésilienne',
    'breakfast': 'petit-déjeuner',
    'british': 'britannique',
    'brunch': 'brunch',
    'bubble_tea': 'bubble tea',
    'burger': 'burgers',
    'burmese': 'birmane',
    'cake': 'gâteaux',
    'cambodian': 'cambodgienne',
    'cantonese': 'cantonaise',
    'caribbean': 'caribéenne',
    'chicken': 'poulet',
    'chinese': 'chinoise',
    'coffee': 'café',
    'coffee_shop': 'salon de café',
    'crepe': 'crêpes',
    'croatian': 'croate',
    'cuban': 'cubaine',
    'curry': 'curry',
    'czech': 'tchèque',
    'danish': 'danoise',
    'deli': 'traiteur',
    'diner': 'diner américain',
    'donut': 'donuts',
    'dumpling': 'raviolis',
    'egyptian': 'égyptienne',
    'ethiopian': 'éthiopienne',
    'falafel': 'falafel',
    'filipino': 'philippine',
    'fine_dining': 'gastronomique',
    'fish': 'poisson',
    'fish_and_chips': 'fish and chips',
    'fondue': 'fondue',
    'french': 'française',
    'fried_food': 'friture',
    'friture': 'friture',
    'frozen_yogurt': 'yaourt glacé',
    'galician': 'galicienne',
    'german': 'allemande',
    'greek': 'grecque',
    'grill': 'grillade',
    'gyros': 'gyros',
    'hawaiian': 'hawaïenne',
    'heuriger': 'Heuriger',
    'hot_dog': 'hot-dog',
    'hotpot': 'fondue chinoise',
    'hunan': 'hunan',
    'hungarian': 'hongroise',
    'ice_cream': 'glaces',
    'indian': 'indienne',
    'indonesian': 'indonésienne',
    'international': 'internationale',
    'iranian': 'iranienne',
    'irish': 'irlandaise',
    'israeli': 'israélienne',
    'italian': 'italienne',
    'jamaican': 'jamaïcaine',
    'japanese': 'japonaise',
    'jewish': 'juive',
    'juice': 'jus',
    'kebab': 'kebab',
    'korean': 'coréenne',
    'korean_fried_chicken': 'poulet frit coréen',
    'lao': 'laotienne',
    'latin_american': 'latino-américaine',
    'lebanese': 'libanaise',
    'local': 'locale',
    'lunch': 'déjeuner',
    'macaroni': 'macaronis',
    'malagasy': 'malgache',
    'malaysian': 'malaisienne',
    'mediterranean': 'méditerranéenne',
    'mexican': 'mexicaine',
    'modern': 'moderne',
    'mongolian': 'mongole',
    'moroccan': 'marocaine',
    'nepalese': 'népalaise',
    'noodle': 'nouilles',
    'okinawan': 'okinawaïenne',
    'oriental': 'orientale',
    'pakistani': 'pakistanaise',
    'pancake': 'pancakes',
    'pasta': 'pâtes',
    'peruvian': 'péruvienne',
    'pie': 'tartes',
    'pizza': 'pizza',
    'poke': 'poké',
    'polish': 'polonaise',
    'portuguese': 'portugaise',
    'ramen': 'ramen',
    'regional': 'régionale',
    'rice': 'riz',
    'romanian': 'roumaine',
    'russian': 'russe',
    'salad': 'salade',
    'sandwich': 'sandwichs',
    'sausage': 'saucisses',
    'savory_pancakes': 'galettes',
    'scandinavian': 'scandinave',
    'seafood': 'fruits de mer',
    'senegalese': 'sénégalaise',
    'serbian': 'serbe',
    'sichuan': 'sichuan',
    'smoothie': 'smoothie',
    'soup': 'soupes',
    'south_african': 'sud-africaine',
    'south_american': 'sud-américaine',
    'south_indian': 'sud-indienne',
    'southeast_asian': 'sud-est asiatique',
    'spanish': 'espagnole',
    'sri_lankan': 'sri-lankaise',
    'steak': 'steak',
    'steak_house': 'steakhouse',
    'sub': 'sous-marins',
    'sushi': 'sushi',
    'swedish': 'suédoise',
    'swiss': 'suisse',
    'syrian': 'syrienne',
    'taco': 'tacos',
    'taiwanese': 'taïwanaise',
    'tapas': 'tapas',
    'tea': 'thé',
    'tex-mex': 'tex-mex',
    'thai': 'thaïlandaise',
    'tibetan': 'tibétaine',
    'tunisian': 'tunisienne',
    'turkish': 'turque',
    'ukrainian': 'ukrainienne',
    'vegan': 'végétalienne',
    'vegetarian': 'végétarienne',
    'vietnamese': 'vietnamienne',
    'waffle': 'gaufres',
    'wings': 'ailes de poulet',
    'wok': 'wok',
    'wrap': 'wraps',
    'yakiniku': 'yakiniku',
    'yemeni': 'yéménite',

    # ===== SPORT =====
    'american_football': 'football américain',
    'archery': 'tir à l\'arc',
    'athletics': 'athlétisme',
    'badminton': 'badminton',
    'baseball': 'baseball',
    'basketball': 'basketball',
    'beachvolleyball': 'beach-volley',
    'billiards': 'billard',
    'bmx': 'BMX',
    'boules': 'pétanque',
    'bowling': 'bowling',
    'boxing': 'boxe',
    'canoe': 'canoë',
    'chess': 'échecs',
    'climbing': 'escalade',
    'cricket': 'cricket',
    'crossfit': 'crossfit',
    'cycling': 'cyclisme',
    'darts': 'fléchettes',
    'diving': 'plongée',
    'equestrian': 'équitation',
    'fencing': 'escrime',
    'fitness': 'fitness',
    'football': 'football',
    'free_flying': 'vol libre',
    'golf': 'golf',
    'gymnastics': 'gymnastique',
    'handball': 'handball',
    'hockey': 'hockey',
    'horse_racing': 'courses hippiques',
    'ice_hockey': 'hockey sur glace',
    'ice_skating': 'patinage sur glace',
    'judo': 'judo',
    'karate': 'karaté',
    'karting': 'karting',
    'kayak': 'kayak',
    'kitesurfing': 'kitesurf',
    'martial_arts': 'arts martiaux',
    'motocross': 'motocross',
    'motor': 'sport automobile',
    'multi': 'multisport',
    'netball': 'netball',
    'padel': 'padel',
    'paintball': 'paintball',
    'paragliding': 'parapente',
    'parkour': 'parkour',
    'pelota': 'pelote basque',
    'pilates': 'pilates',
    'rugby': 'rugby',
    'running': 'course à pied',
    'sailing': 'voile',
    'scuba_diving': 'plongée sous-marine',
    'shooting': 'tir',
    'skateboard': 'skateboard',
    'skating': 'patinage',
    'skiing': 'ski',
    'soccer': 'football',
    'squash': 'squash',
    'surfing': 'surf',
    'swimming': 'natation',
    'table_tennis': 'tennis de table',
    'taekwondo': 'taekwondo',
    'tennis': 'tennis',
    'volleyball': 'volleyball',
    'water_polo': 'water-polo',
    'weightlifting': 'haltérophilie',
    'wrestling': 'lutte',
    'yoga': 'yoga',

    # ===== ATTRIBUTES =====
    'yes': 'oui',
    'no': 'non',
    'limited': 'limité',
    'designated': 'désigné',
    'private': 'privé',
    'customers': 'clients',
    'permissive': 'toléré',
    'wlan': 'WiFi',
    'wifi': 'WiFi',
    'free': 'gratuit',
    'only': 'uniquement',
}

# Enriched descriptions with keywords/synonyms for search
ENRICHMENTS = {
    # ===== AMENITY =====
    'restaurant': "Restaurant. Manger, dîner, déjeuner, repas, table, serveur, menu, carte, plat du jour, cuisine, gastronomique, brasserie, bistrot.",
    'cafe': "Café, salon de thé. Boire un café, petit-déjeuner, pause, goûter, thé, chocolat chaud, croissant, snack, terrasse.",
    'bar': "Bar, débit de boissons. Boire un verre, cocktails, bière, apéro, apéritif, comptoir, soirée, nightlife.",
    'pub': "Pub, taverne. Bière, pinte, ambiance, soirée, alcool, whisky, happy hour.",
    'fast_food': "Fast-food, restauration rapide. Burger, frites, sandwich, kebab, pizza, emporter, à emporter, takeaway, drive.",
    'bank': "Banque, agence bancaire. Argent, compte, crédit, prêt, virement, retrait, conseiller, guichet, coffre.",
    'atm': "Distributeur automatique de billets, DAB, GAB. Retirer de l'argent, espèces, cash, carte bancaire, retrait.",
    'pharmacy': "Pharmacie, officine. Médicaments, ordonnance, santé, pharmacien, parapharmacie, conseil santé.",
    'hospital': "Hôpital, centre hospitalier. Urgences, soins, médecin, santé, clinique, consultation, service médical.",
    'clinic': "Clinique, cabinet médical. Soins, médecin, consultation, spécialiste, chirurgie, santé.",
    'doctors': "Cabinet médical, médecin, docteur. Consultation, rendez-vous médical, généraliste, santé.",
    'dentist': "Dentiste, cabinet dentaire. Dents, soins dentaires, orthodontie, hygiène dentaire.",
    'school': "École, établissement scolaire. Éducation, élèves, primaire, collège, lycée, enseignement.",
    'university': "Université, faculté. Études supérieures, étudiants, campus, licence, master, doctorat.",
    'library': "Bibliothèque, médiathèque. Livres, lecture, emprunter, documents, étude, silence.",
    'cinema': "Cinéma. Film, séance, écran, salle obscure, projection, popcorn, avant-première.",
    'theatre': "Théâtre, salle de spectacle. Pièce, représentation, scène, acteurs, comédie, drame.",
    'parking': "Parking, stationnement. Voiture, garer, place de parking, horodateur, garage.",
    'fuel': "Station-service, station essence. Carburant, essence, diesel, gazole, faire le plein, pompe.",
    'charging_station': "Borne de recharge électrique. Voiture électrique, VE, recharger, électricité, Tesla, charge.",
    'post_office': "Bureau de poste, La Poste. Courrier, colis, lettres, timbres, envoi, affranchissement.",
    'police': "Commissariat, police, gendarmerie. Sécurité, forces de l'ordre, plainte, urgence.",
    'fire_station': "Caserne de pompiers, centre de secours. Incendie, urgence, secours, SDIS.",
    'townhall': "Mairie, hôtel de ville. Administration, services publics, état civil, élections.",
    'marketplace': "Marché, halle. Fruits, légumes, fromage, produits frais, producteurs locaux.",
    'toilets': "Toilettes publiques, WC. Sanitaires, lavabos, accessibles, PMR.",
    'drinking_water': "Point d'eau potable, fontaine. Boire, remplir gourde, eau fraîche, gratuit.",
    'bench': "Banc public. S'asseoir, repos, pause, mobilier urbain, parc.",
    'bicycle_parking': "Parking vélo, arceaux. Garer son vélo, attacher, antivol, stationnement cycliste.",
    'bicycle_rental': "Location de vélos, Vélib. Louer un vélo, vélo en libre-service, vélo partagé.",
    'place_of_worship': "Lieu de culte. Église, mosquée, synagogue, temple, religion, prière, messe.",
    'nightclub': "Discothèque, boîte de nuit, club. Danser, DJ, musique, soirée, fête.",
    'casino': "Casino. Jeux d'argent, machines à sous, poker, roulette, blackjack.",
    'veterinary': "Vétérinaire, clinique vétérinaire. Animaux, chien, chat, soins, vaccins.",
    'kindergarten': "École maternelle, crèche. Petite enfance, enfants, garderie, préscolaire.",
    'nursing_home': "Maison de retraite, EHPAD. Personnes âgées, seniors, soins, hébergement.",
    'community_centre': "Centre communautaire, salle polyvalente, MJC. Activités, associations, réunions.",
    'coworking_space': "Espace de coworking, bureau partagé. Télétravail, freelance, startup, open space.",
    'ice_cream': "Glacier, glaces. Sorbets, cornets, crème glacée, parfums, été.",
    'biergarten': "Jardin à bière, beer garden. Bière, terrasse, extérieur, ambiance, convivial.",
    'swimming_pool': "Piscine. Nager, natation, bassin, plongeon, aquagym, baignade.",
    'gym': "Salle de sport, fitness. Musculation, cardio, entraînement, coach.",
    'spa': "Spa, centre de bien-être. Massage, détente, hammam, sauna, relaxation.",

    # ===== SHOP =====
    'supermarket': "Supermarché, grande surface. Courses, alimentaire, Carrefour, Leclerc, Auchan, caddie.",
    'convenience': "Supérette, épicerie. Dépannage, ouvert tard, proximité, alimentation.",
    'bakery': "Boulangerie. Pain, baguette, croissant, viennoiseries, pâtisserie, tradition.",
    'butcher': "Boucherie. Viande, bœuf, porc, volaille, charcuterie, saucisses, rôti.",
    'greengrocer': "Primeur, marchand de fruits et légumes. Fruits, légumes, frais, saison.",
    'seafood': "Poissonnerie. Poisson, fruits de mer, crevettes, huîtres, moules, frais.",
    'cheese': "Fromagerie. Fromage, camembert, brie, comté, terroir, affinage.",
    'clothes': "Magasin de vêtements, boutique mode. Habits, fringues, prêt-à-porter, mode.",
    'shoes': "Magasin de chaussures. Chaussures, baskets, bottes, sandales, mocassins.",
    'hairdresser': "Coiffeur, salon de coiffure. Couper les cheveux, coupe, brushing, coloration.",
    'beauty': "Institut de beauté, salon esthétique. Soins, manucure, pédicure, épilation, maquillage.",
    'optician': "Opticien. Lunettes, verres, montures, lentilles, vue, ophtalmologie.",
    'jewelry': "Bijouterie, joaillier. Bijoux, bagues, colliers, montres, or, argent.",
    'electronics': "Magasin d'électronique. Téléphone, ordinateur, TV, électroménager, high-tech.",
    'mobile_phone': "Boutique téléphonie. Mobile, smartphone, forfait, réparation écran.",
    'furniture': "Magasin de meubles. Canapé, lit, table, chaises, IKEA, décoration.",
    'florist': "Fleuriste. Fleurs, bouquet, plantes, roses, occasions.",
    'books': "Librairie. Livres, romans, BD, lecture, littérature.",
    'sports': "Magasin de sport. Équipement sportif, Decathlon, running, fitness.",
    'bicycle': "Magasin de vélos. Vélo, VTT, réparation, accessoires cyclisme.",
    'pet': "Animalerie. Animaux, croquettes, accessoires chien chat, aquarium.",
    'hardware': "Quincaillerie. Bricolage, outils, vis, clous, plomberie.",
    'doityourself': "Magasin de bricolage. Castorama, Leroy Merlin, outils, matériaux.",
    'car_repair': "Garage automobile. Mécanique, réparation voiture, entretien, vidange.",
    'laundry': "Laverie automatique. Laver le linge, machine à laver, pressing.",
    'dry_cleaning': "Pressing, teinturerie. Nettoyage à sec, vêtements, costume.",
    'tattoo': "Salon de tatouage. Tatoueur, encre, piercing, body art.",
    'tobacco': "Bureau de tabac. Cigarettes, tabac, jeux, presse, PMU.",
    'newsagent': "Presse, marchand de journaux. Journaux, magazines, loterie.",
    'alcohol': "Cave à vins, magasin d'alcool. Vin, spiritueux, bière artisanale.",
    'organic': "Magasin bio, Biocoop. Produits biologiques, naturel, écologique.",
    'deli': "Traiteur, épicerie fine. Plats préparés, charcuterie, fromage.",
    'copyshop': "Imprimerie, reprographie. Photocopies, impressions, reliure.",
    'travel_agency': "Agence de voyage. Vacances, billets d'avion, séjours, voyages organisés.",
    'video_games': "Magasin de jeux vidéo. Consoles, PS5, Xbox, Nintendo, gaming.",

    # ===== TOURISM =====
    'hotel': "Hôtel. Dormir, nuit, chambre, réservation, hébergement, séjour.",
    'hostel': "Auberge de jeunesse. Dortoir, backpacker, budget, voyageurs.",
    'guest_house': "Chambre d'hôtes, B&B. Hébergement, petit-déjeuner, hôte.",
    'motel': "Motel. Hébergement routier, parking, chambre.",
    'camp_site': "Camping. Tente, caravane, camping-car, plein air, vacances.",
    'caravan_site': "Aire de camping-car. Stationnement, services, vidange.",
    'museum': "Musée. Art, histoire, exposition, culture, visite.",
    'gallery': "Galerie d'art. Exposition, peintures, sculptures, artistes.",
    'zoo': "Zoo, parc zoologique. Animaux, faune, safari.",
    'aquarium': "Aquarium. Poissons, requins, vie marine, océan.",
    'theme_park': "Parc d'attractions. Manèges, attractions, Disney, loisirs.",
    'viewpoint': "Point de vue, belvédère. Panorama, vue, paysage, photo.",
    'information': "Office de tourisme, information. Renseignements, plans, visites.",
    'picnic_site': "Aire de pique-nique. Manger dehors, tables, nature.",

    # ===== LEISURE =====
    'park': "Parc, jardin public. Nature, verdure, promenade, détente, bancs.",
    'garden': "Jardin. Plantes, fleurs, espaces verts, botanique.",
    'playground': "Aire de jeux. Enfants, toboggan, balançoire, jeux extérieurs.",
    'sports_centre': "Centre sportif, complexe sportif. Multisport, gymnase.",
    'fitness_centre': "Salle de sport, club de fitness. Musculation, cardio, coach.",
    'swimming_pool': "Piscine. Natation, bassin, plongeon, cours de natation.",
    'golf_course': "Golf, parcours de golf. Green, clubs, putting.",
    'miniature_golf': "Mini-golf. Loisirs, famille, parcours.",
    'bowling_alley': "Bowling. Quilles, boules, piste, loisirs.",
    'ice_rink': "Patinoire. Patins à glace, hockey, patinage.",
    'escape_game': "Escape game, jeu d'évasion. Énigmes, équipe, immersif.",
    'nature_reserve': "Réserve naturelle. Faune, flore, protection, biodiversité.",
    'marina': "Port de plaisance. Bateaux, voiliers, amarrage.",
    'stadium': "Stade. Match, foot, spectacle sportif, tribune.",
    'horse_riding': "Centre équestre, équitation. Cheval, poney, cours.",
    'dog_park': "Parc canin. Chiens, espace clôturé, animaux.",
    'dance': "École de danse, studio. Cours de danse, ballet, salsa.",
    'water_park': "Parc aquatique. Toboggans, piscines, attractions aquatiques.",

    # ===== CUISINE - Extended =====
    'pizza': "Pizza, pizzeria. Margherita, pepperoni, quatre fromages, four à bois, italien.",
    'burger': "Burgers, hamburgers. Fast-food, frites, steak haché, américain.",
    'sushi': "Sushi, japonais. Maki, sashimi, nigiri, poisson cru, baguettes.",
    'kebab': "Kebab, döner. Viande grillée, sandwich, turc, grec, frites.",
    'chinese': "Cuisine chinoise. Nouilles, riz cantonais, wok, dim sum, canard laqué.",
    'japanese': "Cuisine japonaise. Sushi, ramen, udon, tempura, bento, saké.",
    'indian': "Cuisine indienne. Curry, tandoori, naan, tikka masala, biryani, épices.",
    'thai': "Cuisine thaïlandaise. Pad thaï, curry vert, satay, citronnelle.",
    'vietnamese': "Cuisine vietnamienne. Phở, bo bun, nems, banh mi, frais.",
    'korean': "Cuisine coréenne. Bibimbap, kimchi, BBQ coréen, bulgogi.",
    'mexican': "Cuisine mexicaine. Tacos, burritos, nachos, guacamole, enchiladas.",
    'italian': "Cuisine italienne. Pasta, pâtes, risotto, tiramisu, dolce vita.",
    'french': "Cuisine française. Gastronomie, bistrot, brasserie, terroir, foie gras.",
    'greek': "Cuisine grecque. Gyros, tzatziki, moussaka, feta, méditerranéen.",
    'turkish': "Cuisine turque. Kebab, lahmacun, börek, baklava.",
    'lebanese': "Cuisine libanaise. Mezze, houmous, falafel, taboulé, chawarma.",
    'moroccan': "Cuisine marocaine. Tajine, couscous, pastilla, épices, menthe.",
    'spanish': "Cuisine espagnole. Tapas, paëlla, jamón, tortilla.",
    'vegetarian': "Végétarien, sans viande. Légumes, salades, tofu, healthy.",
    'vegan': "Végétalien, vegan. Sans produit animal, plant-based, éthique.",
    'seafood': "Fruits de mer. Poisson, crevettes, huîtres, moules, homard.",
    'steak_house': "Steakhouse, grill. Viande, bœuf, entrecôte, côte de bœuf.",
    'regional': "Cuisine régionale. Terroir, spécialités locales, tradition.",
    'ice_cream': "Glaces, glacier. Sorbets, crème glacée, cornets, parfums.",
    'coffee_shop': "Coffee shop, salon de café. Espresso, latte, cappuccino, barista.",
    'ramen': "Ramen, nouilles japonaises. Bouillon, porc, œuf, Tokyo.",
    'crepe': "Crêperie. Crêpes, galettes, bretonne, sucrée, salée.",
    'tapas': "Tapas, petites portions. Espagnol, partager, convivial.",
    'sandwich': "Sandwichs, sandwicherie. Sur le pouce, rapide, emporter.",
    'salad': "Salades, healthy. Légumes, frais, léger, diététique.",
    'breakfast': "Petit-déjeuner, brunch. Œufs, bacon, pancakes, matin.",
    'asian': "Cuisine asiatique. Fusion, oriental, baguettes, wok.",
    'mediterranean': "Cuisine méditerranéenne. Huile d'olive, tomate, healthy, soleil.",
    'african': "Cuisine africaine. Mafé, thieboudienne, épices, yassa.",

    # ===== SPORT =====
    'soccer': "Football, foot. Match, ballon rond, terrain, équipe.",
    'tennis': "Tennis. Raquette, court, Roland Garros, simple, double.",
    'basketball': "Basketball, basket. Ballon, panier, terrain, NBA.",
    'swimming': "Natation. Piscine, nager, crawl, brasse, compétition.",
    'cycling': "Cyclisme, vélo. Course, Tour de France, VTT, route.",
    'running': "Course à pied, jogging. Running, marathon, footing, trail.",
    'golf': "Golf. Green, parcours, club, putting, handicap.",
    'fitness': "Fitness, musculation. Salle de sport, cardio, coach.",
    'yoga': "Yoga. Méditation, postures, zen, relaxation, bien-être.",
    'climbing': "Escalade. Bloc, voie, grimper, mur, salle.",
    'skiing': "Ski. Montagne, neige, pistes, alpin, nordique.",
    'martial_arts': "Arts martiaux. Combat, discipline, ceinture, dojo.",
    'equestrian': "Équitation. Cheval, cavalier, manège, saut.",
    'boules': "Pétanque, boules. Terrain, cochonnet, Provence, pastis.",

    # ===== ATTRIBUTES =====
    'wheelchair=yes': "Accessible en fauteuil roulant, PMR. Rampe, ascenseur, mobilité réduite, handicap.",
    'wheelchair=no': "Non accessible en fauteuil roulant. Escaliers, barrières, non adapté PMR.",
    'wheelchair=limited': "Accessibilité limitée. Partiellement accessible, aide possible, PMR avec difficulté.",
    'internet_access=wlan': "WiFi disponible. Internet, connexion, gratuit, réseau.",
    'internet_access=no': "Pas de WiFi. Sans internet, déconnecté.",
    'outdoor_seating=yes': "Terrasse disponible. Extérieur, dehors, plein air, été.",
    'takeaway=yes': "Vente à emporter. Emporter, à emporter, sur le pouce.",
    'delivery=yes': "Livraison disponible. Livraison à domicile, Uber Eats, commande.",
    'drive_through=yes': "Drive, drive-through. Service au volant, voiture, rapide.",
    'smoking=outside': "Fumeurs en terrasse. Cigarette dehors, extérieur autorisé.",
    'smoking=no': "Non-fumeur. Interdit de fumer, sans tabac.",

    # ===== DIET =====
    'diet:vegetarian=yes': "Options végétariennes. Sans viande, légumes, végé.",
    'diet:vegetarian=only': "Entièrement végétarien. Restaurant végé, sans viande.",
    'diet:vegan=yes': "Options végétaliennes, vegan. Sans produit animal.",
    'diet:vegan=only': "Entièrement vegan. 100% végétal, plant-based.",
    'diet:halal=yes': "Options halal. Viande halal, certification.",
    'diet:kosher=yes': "Options casher, kosher. Certification juive.",
    'diet:gluten_free=yes': "Options sans gluten. Intolérance, cœliaque.",
    'diet:lactose_free=yes': "Options sans lactose. Sans lait, intolérance.",

    # ===== PAYMENT =====
    'payment:cash=yes': "Paiement en espèces. Cash, liquide, billets, pièces.",
    'payment:credit_cards=yes': "Carte bancaire acceptée. CB, Visa, Mastercard.",
    'payment:contactless=yes': "Paiement sans contact. NFC, tap, Apple Pay, Google Pay.",
    'payment:debit_cards=yes': "Carte de débit acceptée. Carte bancaire.",
}


def get_enriched_description(key: str, value: str, desc_en: str, desc_fr: str) -> tuple:
    """Generate French translation and enriched description."""

    # Check for combined key=value enrichment
    combined_key = f"{key}={value}"
    if combined_key in ENRICHMENTS:
        enriched = ENRICHMENTS[combined_key]
        # Extract first part as description_fr
        fr = enriched.split('.')[0].strip()
        return fr, enriched

    # Check for value-only enrichment
    if value in ENRICHMENTS:
        enriched = ENRICHMENTS[value]
        fr = enriched.split('.')[0].strip()
        return fr, enriched

    # Get French translation
    if desc_fr and len(desc_fr) > 3:
        fr = desc_fr
    elif value in TRANSLATIONS:
        fr = TRANSLATIONS[value]
    else:
        # Clean and capitalize
        fr = value.replace('_', ' ').replace(';', ', ').title()

    # Build basic enriched description
    enriched = fr

    # Add context based on key type
    if key == 'cuisine':
        enriched = f"Cuisine {fr}."
    elif key == 'sport':
        enriched = f"{fr}. Sport, activité physique."
    elif key in ['diet', 'payment', 'wheelchair', 'internet_access', 'smoking', 'takeaway', 'delivery']:
        enriched = f"{fr}."
    elif desc_en and len(desc_en) > 20:
        # Add first sentence of English description as context
        first_sent = desc_en.split('.')[0]
        if len(first_sent) < 100:
            enriched = f"{fr}. {first_sent}."
    else:
        enriched = f"{fr}."

    return fr, enriched


def main():
    print("=" * 60)
    print("GENERATING ENRICHED DESCRIPTIONS")
    print("=" * 60)

    # Load scraped data
    with open(INPUT_FILE, 'r') as f:
        data = json.load(f)

    print(f"Loaded {len(data)} keys")

    # Load existing enrichments from fr-improved
    existing = {}
    try:
        with open(FR_IMPROVED_FILE, 'r') as f:
            fr_data = json.load(f)
            for tag_key, tag_data in fr_data.items():
                if tag_key.startswith('tag:'):
                    parts = tag_key[4:].split('=', 1)
                    if len(parts) == 2:
                        existing[(parts[0], parts[1])] = {
                            'description_fr': tag_data.get('message', ''),
                            'description_enriched': tag_data.get('improved-message', '')
                        }
        print(f"Loaded {len(existing)} existing enrichments")
    except:
        print("No existing enrichments found")

    # Process all tags
    stats = {'from_existing': 0, 'from_dict': 0, 'generated': 0}

    for key, key_data in data.items():
        for value, vd in key_data['values'].items():
            # Check existing enrichments first
            if (key, value) in existing:
                ex = existing[(key, value)]
                if ex['description_enriched']:
                    vd['description_fr'] = ex['description_fr']
                    vd['description_enriched'] = ex['description_enriched']
                    stats['from_existing'] += 1
                    continue

            # Generate enrichment
            desc_fr, desc_enriched = get_enriched_description(
                key, value,
                vd.get('description_en', ''),
                vd.get('description_fr', '')
            )

            vd['description_fr'] = desc_fr
            vd['description_enriched'] = desc_enriched

            if value in ENRICHMENTS or f"{key}={value}" in ENRICHMENTS:
                stats['from_dict'] += 1
            else:
                stats['generated'] += 1

    # Save result
    with open(OUTPUT_FILE, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    # Print stats
    total = sum(len(kd['values']) for kd in data.values())
    print(f"\nStats:")
    print(f"  Total values: {total}")
    print(f"  From fr-improved.json: {stats['from_existing']}")
    print(f"  From enrichment dictionary: {stats['from_dict']}")
    print(f"  Auto-generated: {stats['generated']}")
    print(f"\nSaved to {OUTPUT_FILE}")


if __name__ == '__main__':
    main()
